#!/usr/bin/env python3
"""
home_ddns.py

用途：
    家里电脑定时 curl VPS 的 /ddns/update 接口。
    本脚本读取请求来源 IP，并更新 Nginx upstream 配置。
    如果 IP 没变，不 reload Nginx。
    如果 IP 变化，则：
        1. 重写 upstream 配置文件
        2. 执行 nginx -t
        3. 执行 systemctl reload nginx

推荐部署路径：
    /opt/home-ddns/home_ddns.py

推荐运行方式：
    使用 systemd 自启动。

一、创建目录并保存脚本：

    sudo mkdir -p /opt/home-ddns
    sudo nano /opt/home-ddns/home_ddns.py
    sudo chmod +x /opt/home-ddns/home_ddns.py

二、创建 systemd service：

    sudo nano /etc/systemd/system/home-ddns.service

内容如下：

    [Unit]
    Description=Home IP updater for Nginx reverse proxy
    After=network-online.target nginx.service
    Wants=network-online.target

    [Service]
    Type=simple
    ExecStart=/usr/bin/python3 /opt/home-ddns/home_ddns.py
    Restart=always
    RestartSec=3
    User=root
    Group=root

    [Install]
    WantedBy=multi-user.target

三、启用自启动并立即运行：

    sudo systemctl daemon-reload
    sudo systemctl enable home-ddns
    sudo systemctl start home-ddns

四、查看运行状态：

    sudo systemctl status home-ddns

五、查看日志：

    journalctl -u home-ddns -f

注意：
    本脚本需要写 Nginx 配置文件，并执行 nginx reload。
    所以最简单方式是以 root 运行。
    如果你想用非 root 运行，需要额外配置 sudoers 权限。
"""

from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from urllib.parse import urlparse, parse_qs
import ipaddress
import os
import re
import subprocess
import sys
import time


# =========================
# 基本配置
# =========================

# 更新接口 token。
# 请务必改成一个足够长、随机、不可猜的字符串。
# 例如：
#   openssl rand -hex 32
TOKEN = "PLEASE_CHANGE_THIS_TO_A_LONG_RANDOM_TOKEN"

# 本服务监听地址。
# 推荐只监听 127.0.0.1，然后由 Nginx 反代过来。
LISTEN_HOST = "127.0.0.1"
LISTEN_PORT = 9000

# 家里网站对外暴露的端口。
# 例如家里路由器上做：
#   WAN:8080 -> 家里电脑:8080
HOME_WEB_PORT = 8080

# Nginx upstream 配置文件。
# 这个文件会由脚本自动生成。
UPSTREAM_FILE = "/etc/nginx/conf.d/home_upstream.conf"

# upstream 名称。
# 你的 Nginx 站点里之后可以写：
#   proxy_pass http://home_backend;
UPSTREAM_NAME = "home_backend"

# 如果你的 VPS 上 Nginx 把真实来源 IP 放在 X-Real-IP，
# 脚本会优先使用这个 header。
# 注意：本服务只监听 127.0.0.1，所以这个 header 是可信的，
# 因为只有本机 Nginx 能访问到它。
REAL_IP_HEADER = "X-Real-IP"

# 是否只接受 IPv4。
# 你的场景大概率是 IPv4 公网地址，所以默认 True。
IPV4_ONLY = True

# nginx 命令路径。
NGINX_BIN = "nginx"
SYSTEMCTL_BIN = "systemctl"


# =========================
# 工具函数
# =========================

def log(message: str):
    now = time.strftime("%Y-%m-%d %H:%M:%S")
    print(f"[{now}] {message}", flush=True)


def validate_ip(ip: str) -> str:
    """
    校验并规范化 IP。
    """
    ip = ip.strip()

    try:
        obj = ipaddress.ip_address(ip)
    except ValueError:
        raise ValueError(f"invalid ip: {ip}")

    if IPV4_ONLY and obj.version != 4:
        raise ValueError(f"only ipv4 is allowed, got: {ip}")

    # 不接受私网地址、回环地址、链路本地地址等。
    # 如果你确定自己的环境特殊，可以放宽这里。
    if obj.is_private or obj.is_loopback or obj.is_link_local or obj.is_multicast or obj.is_unspecified:
        raise ValueError(f"not a public routable ip: {ip}")

    return str(obj)


def get_current_ip_from_file() -> str | None:
    """
    从现有 upstream 文件中解析当前 IP。
    期望文件内容类似：

        upstream home_backend {
            server 1.2.3.4:8080;
        }
    """
    if not os.path.exists(UPSTREAM_FILE):
        return None

    try:
        with open(UPSTREAM_FILE, "r", encoding="utf-8") as f:
            text = f.read()

        pattern = r"server\s+([0-9a-fA-F\.:]+):\d+\s*;"
        match = re.search(pattern, text)

        if not match:
            return None

        return match.group(1)
    except Exception:
        return None


def render_upstream_config(ip: str) -> str:
    """
    生成 Nginx upstream 配置。
    """
    return f"""# This file is automatically generated by home_ddns.py.
# Do not edit manually.

upstream {UPSTREAM_NAME} {{
    server {ip}:{HOME_WEB_PORT};
}}
"""


def atomic_write(path: str, content: str):
    """
    原子写入文件，避免写到一半时 Nginx 读取到半截配置。
    """
    tmp_path = path + ".tmp"

    with open(tmp_path, "w", encoding="utf-8") as f:
        f.write(content)

    os.replace(tmp_path, path)


def run_command(args: list[str]):
    """
    执行命令，并捕获错误输出。
    """
    result = subprocess.run(
        args,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
    )

    if result.returncode != 0:
        raise RuntimeError(
            f"command failed: {' '.join(args)}\n"
            f"stdout:\n{result.stdout}\n"
            f"stderr:\n{result.stderr}"
        )

    return result.stdout.strip()


def update_nginx_upstream(new_ip: str) -> tuple[bool, str]:
    """
    更新 Nginx upstream。
    返回：
        changed: 是否发生变化
        message: 说明
    """
    old_ip = get_current_ip_from_file()

    if old_ip == new_ip:
        return False, f"unchanged: {new_ip}"

    old_content = None
    if os.path.exists(UPSTREAM_FILE):
        with open(UPSTREAM_FILE, "r", encoding="utf-8") as f:
            old_content = f.read()

    new_content = render_upstream_config(new_ip)

    try:
        atomic_write(UPSTREAM_FILE, new_content)

        # 先测试 Nginx 配置。
        run_command([NGINX_BIN, "-t"])

        # 测试通过后平滑重载。
        run_command([SYSTEMCTL_BIN, "reload", "nginx"])

        return True, f"updated: {old_ip} -> {new_ip}"

    except Exception as e:
        # 回滚配置，避免留下坏配置。
        if old_content is not None:
            atomic_write(UPSTREAM_FILE, old_content)
        else:
            try:
                os.remove(UPSTREAM_FILE)
            except FileNotFoundError:
                pass

        raise RuntimeError(f"failed to update nginx upstream: {e}") from e


# =========================
# HTTP Handler
# =========================

class Handler(BaseHTTPRequestHandler):
    def do_GET(self):
        parsed = urlparse(self.path)

        if parsed.path == "/health":
            self.respond(200, "ok\n")
            return

        if parsed.path != "/ddns/update":
            self.respond(404, "not found\n")
            return

        query = parse_qs(parsed.query)
        token = query.get("token", [""])[0]

        if token != TOKEN:
            log(f"forbidden request from {self.client_address[0]}")
            self.respond(403, "forbidden\n")
            return

        # 因为本服务推荐只监听 127.0.0.1，由本机 Nginx 转发过来，
        # 所以优先信任 Nginx 传入的 X-Real-IP。
        raw_ip = self.headers.get(REAL_IP_HEADER)

        if not raw_ip:
            raw_ip = self.client_address[0]

        try:
            new_ip = validate_ip(raw_ip)
        except Exception as e:
            log(f"invalid source ip: {raw_ip}, error: {e}")
            self.respond(400, f"invalid source ip: {e}\n")
            return

        try:
            changed, message = update_nginx_upstream(new_ip)
            log(message)
            self.respond(200, message + "\n")
        except Exception as e:
            log(f"error: {e}")
            self.respond(500, f"error: {e}\n")

    def respond(self, code: int, body: str):
        data = body.encode("utf-8")
        self.send_response(code)
        self.send_header("Content-Type", "text/plain; charset=utf-8")
        self.send_header("Content-Length", str(len(data)))
        self.end_headers()
        self.wfile.write(data)

    def log_message(self, format, *args):
        # 禁用默认 access log，避免重复刷日志。
        return


def main():
    if TOKEN == "PLEASE_CHANGE_THIS_TO_A_LONG_RANDOM_TOKEN":
        log("ERROR: please change TOKEN before running.")
        sys.exit(1)

    server = ThreadingHTTPServer((LISTEN_HOST, LISTEN_PORT), Handler)
    log(f"home-ddns listening on http://{LISTEN_HOST}:{LISTEN_PORT}")
    log(f"upstream file: {UPSTREAM_FILE}")
    log(f"home web port: {HOME_WEB_PORT}")
    server.serve_forever()


if __name__ == "__main__":
    main()
